docker build -t pkemkes/the-gist-of-it-sec-aiapi .\aiapi
docker build -t pkemkes/the-gist-of-it-sec-fetcher .\fetcher
docker build -t pkemkes/the-gist-of-it-sec-backend .\backend
docker build -t pkemkes/the-gist-of-it-sec-database .\database
docker build -t pkemkes/the-gist-of-it-sec-chromadb .\chromadb
docker build -t pkemkes/the-gist-of-it-sec-prometheus .\prometheus
docker build -t pkemkes/the-gist-of-it-sec-loki .\loki
docker build -t pkemkes/the-gist-of-it-sec-grafana .\grafana
docker build -t pkemkes/the-gist-of-it-sec-frontend .\frontend
docker build -t pkemkes/the-gist-of-it-sec-feed-watcher .\feed_watcher