{
 "title": "The Gist of IT Sec - Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total number of active gists added in last 7 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "thegistofitsec",
     "rawSql": "SELECT COUNT(*) FROM thegistofitsec.gists WHERE disabled = FALSE AND published > (UTC_TIMESTAMP() - INTERVAL 7 DAY);"
    }
   ]
  },
  {
   "title": "Number of active gists added in last 7 days by feed",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "thegistofitsec",
     "rawSql": "SELECT (SELECT title FROM thegistofitsec.feeds WHERE id = feed_id) AS \"Feed\", COUNT(feed_id) AS \"# Gists\" FROM thegistofitsec.gists WHERE disabled = FALSE AND published > (UTC_TIMESTAMP() - INTERVAL 7 DAY) GROUP BY feed_id;"
    }
   ]
  },
  {
   "title": "Tag distribution over gists in last 7 days",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "dataset": "thegistofitsec",
     "rawSql": "SELECT \r\n  CONCAT(\r\n    '{',\r\n    REGEXP_REPLACE(\r\n      CONCAT('\"', REPLACE(tags, ';;', '\", \"'), '\"'),\r\n      '\"([^\"]+)\"',\r\n      '\"\\\\1\": 1'\r\n    ),\r\n    '}'\r\n  ) AS 'Tags'\r\n  FROM thegistofitsec.gists \r\n  WHERE disabled = FALSE \r\n    AND published > (UTC_TIMESTAMP() - INTERVAL 7 DAY);"
    }
   ]
  },
  {
   "title": "Total number of disabled gists added in last 7 days",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "thegistofitsec",
     "rawSql": "SELECT COUNT(*) FROM thegistofitsec.gists WHERE disabled = TRUE AND published > (UTC_TIMESTAMP() - INTERVAL 7 DAY);"
    }
   ]
  },
  {
   "title": "Total number of registered Telegram users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "thegistofitsec",
     "rawSql": "SELECT COUNT(*) FROM thegistofitsec.chats;"
    }
   ]
  },
  {
   "title": "Number of disabled gists added in last 7 days by feed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "thegistofitsec",
     "rawSql": "SELECT (SELECT title FROM thegistofitsec.feeds WHERE id = feed_id) AS \"Feed\", COUNT(feed_id) AS \"# Gists\" FROM thegistofitsec.gists WHERE disabled = TRUE AND published > (UTC_TIMESTAMP() - INTERVAL 7 DAY) GROUP BY feed_id;"
    }
   ]
  },
  { "title": "Gists Bot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Time spent to process all gists",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "process_all_entries_seconds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Time spent to process a single gist by feed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_entry_seconds_sum[1m]) / rate(process_entry_seconds_count[1m])",
     "legendFormat": "{{feed_title}}"
    }
   ]
  },
  {
   "title": "Time spent to upsert a gist by feed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(upsert_gist_seconds_sum[1m]) / rate(upsert_gist_seconds_count[1m])",
     "legendFormat": "{{feed_title}}"
    }
   ]
  },
  {
   "title": "Time spent to upsert a search result by feed",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(upsert_search_result_seconds_sum[1m]) / rate(upsert_search_result_seconds_count[1m])",
     "legendFormat": "{{feed_title}}"
    }
   ]
  },
  {
   "title": "Time spent to summarize a single gist",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(summarize_entry_seconds_sum[1m]) / rate(summarize_entry_seconds_count[1m])",
     "legendFormat": "Time spent"
    }
   ]
  },
  {
   "title": "Time spent to get a single search result",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(get_search_results_seconds_sum[1m]) / rate(get_search_results_seconds_count[1m])",
     "legendFormat": "Time spent"
    }
   ]
  },
  { "title": "REST Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "API response times by path and status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{path!=\"/health\"}[5m]) / rate(flask_http_request_duration_seconds_count{path!=\"/health\"}[5m])",
     "legendFormat": "{{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Amount of requests by path in last 24 hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(flask_http_request_duration_seconds_count{path!=\"/health\"}) by (path)) - (sum(flask_http_request_duration_seconds_count{path!=\"/health\"} offset 24h) by (path))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Amount of requests by status in last 24 hours",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(flask_http_request_duration_seconds_count{path!=\"/health\"}) by (status)) - (sum(flask_http_request_duration_seconds_count{path!=\"/health\"} offset 24h) by (status))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Health Route response times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{path=\"/health\"}[5m]) / rate(flask_http_request_duration_seconds_count{path=\"/health\"}[5m])",
     "legendFormat": "{{path}} - {{status}}"
    }
   ]
  },
  {
   "title": "Clean Up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time spent to cleanup all gists",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "cleanup_gists_seconds", "legendFormat": "Time spent" }
     ]
    },
    {
     "title": "Number of gists that have been checked in a single cleanup run",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "gists_checked", "legendFormat": "Gists checked" }
     ]
    },
    {
     "title": "Time spent to check a single gist",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(check_gist_seconds_sum[1m]) / rate(check_gist_seconds_count[1m])",
       "legendFormat": "{{feed_title}}"
      }
     ]
    },
    {
     "title": "Time spent to cleanup gist in database",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ensure_correct_disabled_seconds_sum[1m]) / rate(ensure_correct_disabled_seconds_count[1m])",
       "legendFormat": "{{feed_title}} - Should be disabled: {{should_be_disabled}}; Is disabled: {{is_disabled}}"
      }
     ]
    },
    {
     "title": "Time spent to cleanup gist in chromadb",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ensure_chromadb_seconds_sum[1m]) / rate(ensure_chromadb_seconds_count[1m])",
       "legendFormat": "{{feed_title}} - Should be disabled: {{should_be_disabled}}; Is disabled: {{is_disabled}}, Feed id in DB: {{feed_id_in_db}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Telegram Bot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time spent to process all chats",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "process_chats", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}