CREATE DATABASE IF NOT EXISTS TheGistOfItSec;

USE TheGistOfItSec;

CREATE TABLE IF NOT EXISTS Feeds (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Title TEXT NOT NULL,
    RssUrl MEDIUMTEXT NOT NULL,
    Language TINYTEXT,
    UNIQUE(RssUrl)
);

CREATE INDEX IF NOT EXISTS FeedsByRssUrl ON Feeds(RssUrl);

CREATE TABLE IF NOT EXISTS Gists (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Reference TEXT NOT NULL,
    FeedId INT NOT NULL,
    Author TEXT NOT NULL,
    Title TEXT NOT NULL,
    Published DATETIME NOT NULL,
    Updated DATETIME NOT NULL,
    Url MEDIUMTEXT NOT NULL,
    Summary LONGTEXT NOT NULL,
    Tags LONGTEXT NOT NULL,
    SearchQuery MEDIUMTEXT NOT NULL,
    Disabled BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (FeedId) REFERENCES Feeds(Id),
    FULLTEXT(Summary),
    FULLTEXT(Tags),
    UNIQUE(Reference)
);

CREATE INDEX IF NOT EXISTS GistsByReference ON Gists(Reference);
CREATE INDEX IF NOT EXISTS GistsByUpdated ON Gists(Updated);

CREATE TABLE IF NOT EXISTS Chats (
    Id BIGINT PRIMARY KEY,
    GistIdLastSent INT
);

CREATE TABLE IF NOT EXISTS SearchResults (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    GistId INT NOT NULL,
    Title TEXT NOT NULL,
    Snippet MEDIUMTEXT NOT NULL,
    Url MEDIUMTEXT NOT NULL,
    DisplayUrl TEXT NOT NULL,
    ThumbnailUrl MEDIUMTEXT,
    FOREIGN KEY (GistId) REFERENCES Gists(Id)
);

CREATE TABLE IF NOT EXISTS RecapsDaily (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Created DATETIME NOT NULL,
    Recap LONGTEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS RecapsDailyByCreated ON RecapsDaily(Created);

CREATE TABLE IF NOT EXISTS RecapsWeekly (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Created DATETIME NOT NULL,
    Recap LONGTEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS RecapsWeeklyByCreated ON RecapsWeekly(Created);