# #!/bin/bash
set -e

mariadb --user=root --password="$MARIADB_ROOT_PASSWORD" <<-EOSQL
  CREATE USER IF NOT EXISTS '${DB_GISTSERVICE_USERNAME}'@'%' IDENTIFIED BY '${DB_GISTSERVICE_PASSWORD}';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.Gists TO '${DB_GISTSERVICE_USERNAME}'@'%';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.Summaries TO '${DB_GISTSERVICE_USERNAME}'@'%';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.Feeds TO '${DB_GISTSERVICE_USERNAME}'@'%';

  CREATE USER IF NOT EXISTS '${DB_RECAPSERVICE_USERNAME}'@'%' IDENTIFIED BY '${DB_RECAPSERVICE_PASSWORD}';
  GRANT SELECT on TheGistOfItSec.Gists TO '${DB_RECAPSERVICE_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Summaries TO '${DB_RECAPSERVICE_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Feeds TO '${DB_RECAPSERVICE_USERNAME}'@'%';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.RecapsDaily TO '${DB_RECAPSERVICE_USERNAME}'@'%';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.RecapsWeekly TO '${DB_RECAPSERVICE_USERNAME}'@'%';

  CREATE USER IF NOT EXISTS '${DB_GISTSCONTROLLER_USERNAME}'@'%' IDENTIFIED BY '${DB_GISTSCONTROLLER_PASSWORD}';
  GRANT SELECT on TheGistOfItSec.Gists TO '${DB_GISTSCONTROLLER_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Summaries TO '${DB_GISTSCONTROLLER_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Feeds TO '${DB_GISTSCONTROLLER_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.RecapsDaily TO '${DB_GISTSCONTROLLER_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.RecapsWeekly TO '${DB_GISTSCONTROLLER_USERNAME}'@'%';
  
  CREATE USER IF NOT EXISTS '${DB_TELEGRAMSERVICE_USERNAME}'@'%' IDENTIFIED BY '${DB_TELEGRAMSERVICE_PASSWORD}';
  GRANT SELECT on TheGistOfItSec.Gists TO '${DB_TELEGRAMSERVICE_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Summaries TO '${DB_TELEGRAMSERVICE_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Feeds TO '${DB_TELEGRAMSERVICE_USERNAME}'@'%';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.Chats TO '${DB_TELEGRAMSERVICE_USERNAME}'@'%';

  CREATE USER IF NOT EXISTS '${DB_CLEANUPSERVICE_USERNAME}'@'%' IDENTIFIED BY '${DB_CLEANUPSERVICE_PASSWORD}';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.Gists TO '${DB_CLEANUPSERVICE_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Feeds TO '${DB_CLEANUPSERVICE_USERNAME}'@'%';
  
  CREATE USER IF NOT EXISTS '${DB_GRAFANA_USERNAME}'@'%' IDENTIFIED BY '${DB_GRAFANA_PASSWORD}';
  GRANT SELECT on TheGistOfItSec.Gists TO '${DB_GRAFANA_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Summaries TO '${DB_GRAFANA_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Feeds TO '${DB_GRAFANA_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Chats TO '${DB_GRAFANA_USERNAME}'@'%';

  FLUSH PRIVILEGES;
EOSQL