# #!/bin/bash
set -e

mariadb --user=root --password="$MARIADB_ROOT_PASSWORD" <<-EOSQL
  CREATE USER IF NOT EXISTS '${DB_GISTSERVICE_USERNAME}'@'%' IDENTIFIED BY '${DB_GISTSERVICE_PASSWORD}';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.Gists TO '${DB_GISTSERVICE_USERNAME}'@'%';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.Feeds TO '${DB_GISTSERVICE_USERNAME}'@'%';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.SearchResults TO '${DB_GISTSERVICE_USERNAME}'@'%';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.RecapsDaily TO '${DB_GISTSERVICE_USERNAME}'@'%';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.RecapsWeekly TO '${DB_GISTSERVICE_USERNAME}'@'%';

  CREATE USER IF NOT EXISTS '${DB_RESTAPI_USERNAME}'@'%' IDENTIFIED BY '${DB_RESTAPI_PASSWORD}';
  GRANT SELECT on TheGistOfItSec.Gists TO '${DB_RESTAPI_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Feeds TO '${DB_RESTAPI_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.SearchResults TO '${DB_RESTAPI_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.RecapsDaily TO '${DB_RESTAPI_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.RecapsWeekly TO '${DB_RESTAPI_USERNAME}'@'%';
  
  CREATE USER IF NOT EXISTS '${DB_TELEGRAMBOT_USERNAME}'@'%' IDENTIFIED BY '${DB_TELEGRAMBOT_PASSWORD}';
  GRANT SELECT on TheGistOfItSec.Gists TO '${DB_TELEGRAMBOT_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Feeds TO '${DB_TELEGRAMBOT_USERNAME}'@'%';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.Chats TO '${DB_TELEGRAMBOT_USERNAME}'@'%';

  CREATE USER IF NOT EXISTS '${DB_CLEANUPBOT_USERNAME}'@'%' IDENTIFIED BY '${DB_CLEANUPBOT_PASSWORD}';
  GRANT SELECT, INSERT, UPDATE, DELETE on TheGistOfItSec.Gists TO '${DB_CLEANUPBOT_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Feeds TO '${DB_CLEANUPBOT_USERNAME}'@'%';
  
  CREATE USER IF NOT EXISTS '${DB_GRAFANA_USERNAME}'@'%' IDENTIFIED BY '${DB_GRAFANA_PASSWORD}';
  GRANT SELECT on TheGistOfItSec.Gists TO '${DB_GRAFANA_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Feeds TO '${DB_GRAFANA_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.SearchResults TO '${DB_GRAFANA_USERNAME}'@'%';
  GRANT SELECT on TheGistOfItSec.Chats TO '${DB_GRAFANA_USERNAME}'@'%';

  FLUSH PRIVILEGES;
EOSQL